### ISSUE TITLE
Show distance or time elapsed before each song

### ISSUE THREAD

**Issue by jacbmelo** [amourao/effortly#3]
The lines should start with the distance or time elapsed:

```
1,5 km (5:00 /km): New Order - True Faith
3,0 km (4:48 /km): Dan Terminus - Cherenkov Blue Overdriver
...
```

Or:

```
0:05:36 (5:00 /km): New Order - True Faith
0:10:15 (4:48 /km): Dan Terminus - Cherenkov Blue Overdriver
...
```

That way we can understand where we were when the song was playing.

**Comment by amourao** [comment]
![image](https://user-images.githubusercontent.com/2866295/81206701-65a69780-8fc4-11ea-967c-7cf6626684b1.png)

This is now an option you can select in the settings, and will be applied from now forward:
![image](https://user-images.githubusercontent.com/2866295/81206560-31cb7200-8fc4-11ea-8474-ade7c15f1192.png)

**Comment by amourao** [comment]
@jacbmelo, let me know if this is working for you

**Comment by jacbmelo** [comment]
Infelizmente não está a funcionar para mim (unfortunately it's not working for me):

<img width="394" alt="Captura de ecrã 2020-05-13, às 00 48 07" src="https://user-images.githubusercontent.com/1490766/81756554-f513e500-94b3-11ea-9660-936477ceb608.png">

<img width="755" alt="Captura de ecrã 2020-05-13, às 00 53 27" src="https://user-images.githubusercontent.com/1490766/81756643-386e5380-94b4-11ea-9fd8-cd310b7b92d4.png">

**Comment by amourao** [comment]
It will work for all activities from now forward.

I've synced the message manually for this activity, and I'll do a script to update all your old activities to the new format
![image](https://user-images.githubusercontent.com/2866295/81757818-03fc9680-94b8-11ea-841e-df940fd3d9e1.png)

**Comment by jacbmelo** [comment]
Muito obrigado. Não preciso que sincronizes todas as atividades anteriores. Esta atividade de ontem foi feita depois de ter alterado as definições na aplicação Effortly. Por isso é que eu achava que não estava a funcionar para o meu user.

Thank you. I don't need you to sync all previous activities. This activity from yesterday was done after changing the settings in the Effortly application. That's why I thought it wasn't working for my user.
